#!/bin/bash
# this is a stripped down version of https://github.com/ckuethe/usbarmory/wiki/USB-Gadgets - I don't claim any rights

modprobe libcomposite
cd /sys/kernel/config/usb_gadget/
mkdir -p g1
cd g1
echo 0x1881 > idVendor # Linux Foundation
echo 0x0150 > idProduct # Multifunction Composite Gadget
echo 0x0057 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB # USB2
echo 0x03 > bInterfaceClass
echo 0xef > bDeviceClass # HID
mkdir -p strings/0x409
echo "iclicker" > strings/0x409/serialnumber
echo "iclicker" > strings/0x409/manufacturer
echo "iclicker USB Base" > strings/0x409/product
N="usb0"
# Add functions
# HID
mkdir -p functions/hid.$N
echo 0 > functions/hid.usb0/protocol
echo 0 > functions/hid.usb0/subclass
echo 8 > functions/hid.usb0/report_length
echo -ne \\x05\\x0c\\x09\\x01\\xa1\\x01\\x06\\x00\\xff\\x09\\x01\\x15\\x00\\x26\\xff\\x00\\x95\\x40\\x75\\x08\\x81\\x02\\xa1\\x02\\x06\\x00\\xff\\x09\\x01\\x15\\x00\\x26\\xff\\x00\\x95\\x40\\x75\\x08\\x91\\x02\\xc0\\xc0 > functions/hid.usb0/report_desc
C=1
mkdir -p configs/c.$C/strings/0x409
#echo "Config $C: ECM network" > configs/c.$C/strings/0x409/configuration
echo 250 > configs/c.$C/MaxPower
ln -s functions/hid.$N configs/c.$C/

#Serial
#mkdir -p functions/acm.$N
#ln -s functions/acm.$N configs/c.$C/

# Ethernet
#mkdir -p functions/ecm.usb0
#HOST="48:6f:73:74:50:43"
#SELF="42:61:64:55:53:42"
#echo $HOST > functions/ecm.usb0/host_addr
#echo $SELF > functions/ecm.usb0/dev_addr
#ln -s functions/ecm.$N configs/c.$C/

# End of Functions
ls /sys/class/udc > UDC

#ifconfig usb0 10.0.0.1 netmask 255.255.255.252 up
#route add -net default gw 10.0.0.2
